version: '3'
services:
  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4040:3333"  # Updated port mapping to 3333
    environment:
      - PORT=3333  # Set the port for the API
    restart: unless-stopped
    command: ["./node_modules/.bin/pm2-runtime", "start", "ecosystem.config.js"]  # Updated command to use PM2
