version: '3'
services:
  backend-api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3232:3232"  # Updated port mapping to 3232
    environment:
      - PORT=3232  # Set the port for the API
    restart: unless-stopped
    command: ["npm", "run", "start"] #["./node_modules/.bin/pm2-runtime", "start", "ecosystem.config.js"]  # Updated command to use PM2
